# Generated by Django 6.1 on 2026-09-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmember_last_seen_at'),
        ('notifications', '0001_initial'),
        ('users', '0003_userprofile_blinkit_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('expense_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('lines', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='users.userprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='groups.group')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='notificatio_group_i_8e731c_idx')],
            },
        ),
    ]
