# Generated by Django 6.1 on 2026-08-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_password_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blinkit_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blinkit_auth_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blinkit_device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blinkit_session_uuid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="swiggy_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="swiggy_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
