# Generated by Django 6.1 on 2026-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_blinkit_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
