# Generated by Django 6.1 on 2026-08-30 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
