# Generated by Django 6.1 on 2026-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_date_alter_settlement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
