# Generated by Django 6.1 on 2026-09-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expense_notes"),
        ("users", "0003_userprofile_blinkit_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryOrderRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("order_id", models.CharField(max_length=100)),
                ("placed_at", models.CharField(blank=True, default="", max_length=100)),
                ("total_amount", models.FloatField(default=0.0)),
                ("other_charges", models.FloatField(default=0.0)),
                ("product_names", models.JSONField(default=list)),
                ("item_details", models.JSONField(default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_orders",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "unique_together": {("user", "platform", "order_id")},
            },
        ),
    ]
