# Generated by Django 6.1 on 2026-09-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_groceryorderrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="groceryorderrecord",
            name="full_order_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="GroceryOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(default=0.0)),
                ("quantity", models.IntegerField(default=1)),
                ("item_json", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="expenses.groceryorderrecord",
                    ),
                ),
            ],
        ),
    ]
