# Generated by Django 6.1 on 2026-09-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_groceryorderrecord_full_order_json_groceryorderitem'),
        ('users', '0003_userprofile_blinkit_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_settlements', to='users.userprofile'),
        ),
    ]
