# Generated by Django 6.1 on 2026-09-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
